"""
KoboScript Generator — Streamlit version
Run:  streamlit run kobo_script_app.py
"""

import streamlit as st
import streamlit.components.v1 as components
import json, requests, re, os
from threading import Thread

CONFIG_FILE = "generator_config.json"

# ─────────────────────────────────────────────────────────────────
# Config helpers
# ─────────────────────────────────────────────────────────────────
def load_cfg():
    try:
        with open(CONFIG_FILE) as f: return json.load(f)
    except: return {}

def save_cfg(d):
    try:
        with open(CONFIG_FILE, "w") as f: json.dump(d, f, indent=2)
    except: pass

# ─────────────────────────────────────────────────────────────────
# Script Generator — identical logic to the tkinter version
# ─────────────────────────────────────────────────────────────────
def generate_script(token, asset_uid, sheet_name, fields_list,
                    date_from, date_to, interval, kobo_url):

    fields_js = json.dumps(fields_list)

    if date_from or date_to:
        d_from = (date_from or "2010-01-01") + "T00:00:00"
        d_to   = (date_to   or "2099-12-31") + "T23:59:59"
        date_block = (
            '  // Date filter\n'
            '  var dateQuery = encodeURIComponent(JSON.stringify({\n'
            '    "_submission_time": {"$gte": "' + d_from + '", "$lte": "' + d_to + '"}\n'
            '  }));\n'
            '  nextUrl = nextUrl + "?query=" + dateQuery;\n'
        )
    else:
        date_block = ""

    fields_line = (
        "  var FIELDS = " + fields_js + ";"
        if fields_list else
        "  var FIELDS = []; // empty = use all fields"
    )

    L = []

    L += [
        '// ╔══════════════════════════════════════════════════════════════╗',
        '// ║          KoboSync — Google Apps Script                      ║',
        '// ║          Auto-generated by KoboScript Generator             ║',
        '// ╚══════════════════════════════════════════════════════════════╝',
        '//',
        '// الخطوات:',
        '//  1. افتح Google Sheets → Extensions → Apps Script',
        '//  2. الصق الكود كاملاً → Save (Ctrl+S)',
        '//  3. شغّل setupTrigger() مرة واحدة فقط',
        '//  4. خلاص — يسينك كل ' + str(interval) + ' دقيقة تلقائياً',
        '',
        'var CONFIG = {',
        '  KOBO_TOKEN  : "' + token + '",',
        '  ASSET_UID   : "' + asset_uid + '",',
        '  SHEET_NAME  : "' + sheet_name + '",',
        '  KOBO_BASE   : "' + kobo_url.rstrip('/') + '",',
        '  INTERVAL_MIN: ' + str(interval),
        '};',
        '',
    ]

    L += [
        '// ── شغّل هذه الدالة مرة واحدة لتفعيل الـ Trigger ─────────────',
        'function setupTrigger() {',
        '  var triggers = ScriptApp.getProjectTriggers();',
        '  for (var i = 0; i < triggers.length; i++) {',
        '    if (triggers[i].getHandlerFunction() === "syncNewData") {',
        '      ScriptApp.deleteTrigger(triggers[i]);',
        '    }',
        '  }',
        '  ScriptApp.newTrigger("syncNewData")',
        '    .timeBased()',
        '    .everyMinutes(CONFIG.INTERVAL_MIN)',
        '    .create();',
        '  Logger.log("Trigger set: every " + CONFIG.INTERVAL_MIN + " minutes");',
        '  SpreadsheetApp.getActiveSpreadsheet().toast(',
        '    "Syncing every " + CONFIG.INTERVAL_MIN + " min",',
        '    "KoboSync Active", 5',
        '  );',
        '}',
        '',
    ]

    L += [
        '// ── Wrapper للتشغيل اليدوي ─────────────────────────────────────',
        'function syncNewData() {',
        '  try { syncNewData_(); }',
        '  catch(e) { Logger.log("ERROR: " + e.message + "\\n" + e.stack); }',
        '}',
        '',
    ]

    L += [
        '// ── الدالة الرئيسية — يشغّلها الـ Trigger تلقائياً ──────────────',
        'function syncNewData_() {',
        fields_line,
        '',
        '  var ss    = SpreadsheetApp.getActiveSpreadsheet();',
        '  var sheet = ss.getSheetByName(CONFIG.SHEET_NAME);',
        '  if (!sheet) {',
        '    sheet = ss.insertSheet(CONFIG.SHEET_NAME);',
        '    Logger.log("Created sheet: " + CONFIG.SHEET_NAME);',
        '  }',
        '',
        '  var allData = fetchAllKoboData_();',
        '  if (!allData || allData.length === 0) {',
        '    Logger.log("No data returned from Kobo");',
        '    return;',
        '  }',
        '',
        '  var lastCol = sheet.getLastColumn();',
        '  var lastRow = sheet.getLastRow();',
        '  var headers = (lastRow > 0 && lastCol > 0)',
        '                  ? sheet.getRange(1, 1, 1, lastCol).getValues()[0]',
        '                  : [];',
        '',
        '  if (headers.length === 0 || (headers.length === 1 && headers[0] === "")) {',
        '    headers = (FIELDS.length > 0) ? FIELDS : Object.keys(allData[0]);',
        '    if (headers.indexOf("_uuid") === -1) headers.unshift("_uuid");',
        '    sheet.getRange(1, 1, 1, headers.length).setValues([headers]);',
        '    sheet.getRange(1, 1, 1, headers.length)',
        '         .setBackground("#1A3A5C").setFontColor("#FFFFFF").setFontWeight("bold");',
        '    sheet.setFrozenRows(1);',
        '    Logger.log("Headers written: " + headers.length + " columns");',
        '  }',
        '',
        '  var uuidCol  = headers.indexOf("_uuid");',
        '  var existing = {};',
        '  if (uuidCol >= 0 && sheet.getLastRow() > 1) {',
        '    var uuidVals = sheet.getRange(2, uuidCol + 1, sheet.getLastRow() - 1, 1).getValues();',
        '    for (var i = 0; i < uuidVals.length; i++) {',
        '      if (uuidVals[i][0]) existing[uuidVals[i][0]] = true;',
        '    }',
        '  }',
        '',
        '  var cols    = (FIELDS.length > 0) ? FIELDS : headers;',
        '  var newRows = [];',
        '  for (var r = 0; r < allData.length; r++) {',
        '    var rec  = allData[r];',
        '    var uuid = String(rec["_uuid"] || "");',
        '    if (existing[uuid]) continue;',
        '    var row = [];',
        '    for (var c = 0; c < cols.length; c++) {',
        '      var v = rec[cols[c]];',
        '      if (v === null || v === undefined) v = "";',
        '      if (typeof v === "object") v = JSON.stringify(v);',
        '      row.push(String(v));',
        '    }',
        '    newRows.push(row);',
        '  }',
        '',
        '  if (newRows.length === 0) { Logger.log("No new records"); return; }',
        '',
        '  sheet.getRange(sheet.getLastRow() + 1, 1, newRows.length, newRows[0].length)',
        '       .setValues(newRows);',
        '  Logger.log("Synced " + newRows.length + " new record(s)");',
        '',
        '  try { logSync_(newRows.length, allData.length); } catch(e) {}',
        '}',
        '',
    ]

    L += [
        '// ── جلب كل الصفحات من Kobo مع دعم Pagination ──────────────────',
        'function fetchAllKoboData_() {',
        '  var results = [];',
        '  var options = {',
        '    headers: {',
        '      "Authorization": "Token " + CONFIG.KOBO_TOKEN,',
        '      "Accept": "application/json"',
        '    },',
        '    muteHttpExceptions: true',
        '  };',
        '  var nextUrl = CONFIG.KOBO_BASE + "/api/v2/assets/" + CONFIG.ASSET_UID + "/data/";',
    ]
    if date_block:
        L.append(date_block)
    L += [
        '  while (nextUrl) {',
        '    var res  = UrlFetchApp.fetch(nextUrl, options);',
        '    var code = res.getResponseCode();',
        '    if (code !== 200) {',
        '      Logger.log("HTTP " + code + ": " + res.getContentText().substring(0, 300));',
        '      break;',
        '    }',
        '    var data = JSON.parse(res.getContentText());',
        '    if (Array.isArray(data)) {',
        '      results = results.concat(data); nextUrl = null;',
        '    } else {',
        '      results = results.concat(data.results || []);',
        '      nextUrl  = data.next || null;',
        '      Logger.log("Page: " + (data.results||[]).length + " | Total: " + results.length);',
        '    }',
        '  }',
        '  return results;',
        '}',
        '',
    ]

    L += [
        '// ── تسجيل في _SyncLog ───────────────────────────────────────────',
        'function logSync_(n, total) {',
        '  var ss  = SpreadsheetApp.getActiveSpreadsheet();',
        '  var log = ss.getSheetByName("_SyncLog");',
        '  if (!log) {',
        '    log = ss.insertSheet("_SyncLog");',
        '    log.getRange(1,1,1,4).setValues([["Timestamp","New","Total","Sheet"]]);',
        '    log.getRange(1,1,1,4).setBackground("#1A3A5C").setFontColor("#fff").setFontWeight("bold");',
        '  }',
        '  log.appendRow([new Date().toISOString(), n, total, CONFIG.SHEET_NAME]);',
        '}',
        '',
    ]

    L += [
        '// ── تشغيل يدوي ─────────────────────────────────────────────────',
        'function runNow() {',
        '  syncNewData_();',
        '  SpreadsheetApp.getActiveSpreadsheet().toast("Done!", "KoboSync", 3);',
        '}',
        '',
        '// ── فحص الاتصال بدون كتابة ─────────────────────────────────────',
        'function debugFetch() {',
        '  var data = fetchAllKoboData_();',
        '  Logger.log("Fetched: " + data.length + " records");',
        '  if (data.length > 0) Logger.log("First _uuid: " + data[0]["_uuid"]);',
        '  else Logger.log("No data — check TOKEN and ASSET_UID in CONFIG");',
        '}',
    ]

    return "\n".join(L)


# ─────────────────────────────────────────────────────────────────
# Streamlit UI
# ─────────────────────────────────────────────────────────────────
def main():
    st.set_page_config(
        page_title="KoboScript Generator",
        page_icon="⬡",
        layout="wide",
    )

    st.title("⬡ KoboScript Generator")
    st.caption("Generate Google Apps Script → Paste → Auto-sync Kobo → Google Sheets")
    st.divider()

    cfg = load_cfg()
    date_pat = re.compile(r'^\d{4}-\d{2}-\d{2}$')

    # ── Layout: left settings | right code ───────────────────────
    left, right = st.columns([1, 1], gap="large")

    with left:
        # ── KOBO SERVER ──────────────────────────────────────────
        st.subheader("🌐 Kobo Server")
        kobo_url = st.selectbox(
            "Server", label_visibility="collapsed",
            options=[
                "https://kobo.unhcr.org",
                "https://kf.kobotoolbox.org",
                "https://kobo.humanitarianresponse.info",
            ],
            index=(["https://kobo.unhcr.org",
                    "https://kf.kobotoolbox.org",
                    "https://kobo.humanitarianresponse.info"
                    ].index(cfg.get("kobo_url", "https://kobo.unhcr.org"))
                   if cfg.get("kobo_url") in [
                       "https://kobo.unhcr.org",
                       "https://kf.kobotoolbox.org",
                       "https://kobo.humanitarianresponse.info"] else 0),
        )

        # ── API TOKEN ─────────────────────────────────────────────
        st.subheader("🔑 API Token")
        token = st.text_input(
            "Token", value=cfg.get("token", ""),
            type="password", label_visibility="collapsed",
            placeholder="Paste your Kobo API token...",
        )

        if st.button("📋 Load Projects", use_container_width=True):
            if not token:
                st.error("Enter API token first.")
            else:
                with st.spinner("Loading projects..."):
                    try:
                        r = requests.get(
                            kobo_url.rstrip("/") + "/api/v2/assets/?format=json&asset_type=survey",
                            headers={"Authorization": f"Token {token}"}, timeout=20)
                        r.raise_for_status()
                        results = r.json().get("results", [])
                        st.session_state["projects"] = {
                            f"{a['name']}  ({a.get('deployment__submission_count','?')} submissions)": a
                            for a in results
                        }
                        st.success(f"✓ {len(results)} project(s) loaded")
                    except Exception as e:
                        st.error(f"Failed: {e}")

        # ── PROJECT ───────────────────────────────────────────────
        st.subheader("📄 Project")
        projects = st.session_state.get("projects", {})
        proj_label = st.selectbox(
            "Project", label_visibility="collapsed",
            options=list(projects.keys()),
            placeholder="Load projects first...",
            disabled=not projects,
        )
        project = projects.get(proj_label)
        if project:
            st.caption(f"UID: `{project['uid']}`")

        # Load fields when project changes
        if project and st.session_state.get("last_uid") != project["uid"]:
            with st.spinner("Loading fields..."):
                try:
                    r = requests.get(
                        f"{kobo_url.rstrip('/')}/api/v2/assets/{project['uid']}/data/?format=json&limit=1",
                        headers={"Authorization": f"Token {token}"}, timeout=20)
                    r.raise_for_status()
                    resp    = r.json()
                    results = resp.get("results", resp) if isinstance(resp, dict) else resp
                    if results:
                        st.session_state["fields"]   = list(results[0].keys())
                        st.session_state["last_uid"] = project["uid"]
                        # Default: all selected
                        st.session_state["sel_fields"] = {
                            f: True for f in st.session_state["fields"]
                        }
                        st.success(f"✓ {len(st.session_state['fields'])} fields loaded")
                    else:
                        st.warning("No submissions found for this project.")
                except Exception as e:
                    st.error(f"Failed to load fields: {e}")

        # ── FIELDS ────────────────────────────────────────────────
        st.subheader("🗂 Fields to Sync")
        all_fields = st.session_state.get("fields", [])

        if all_fields:
            # Search + select all / none
            fc1, fc2, fc3 = st.columns([2, 1, 1])
            search = fc1.text_input("🔍 Search fields", label_visibility="collapsed",
                                     placeholder="Search...", key="field_search")
            if fc2.button("✅ All",  use_container_width=True):
                for f in all_fields: st.session_state["sel_fields"][f] = True
            if fc3.button("❌ None", use_container_width=True):
                for f in all_fields: st.session_state["sel_fields"][f] = False

            filtered = [f for f in all_fields if search.lower() in f.lower()] if search else all_fields
            sel = st.session_state.get("sel_fields", {f: True for f in all_fields})

            # Show as a scrollable multi-column grid of checkboxes
            with st.container(height=220):
                cols = st.columns(2)
                for i, field in enumerate(filtered):
                    checked = sel.get(field, True)
                    new_val = cols[i % 2].checkbox(field, value=checked, key=f"chk_{field}")
                    st.session_state["sel_fields"][field] = new_val

            selected_count = sum(1 for v in sel.values() if v)
            st.caption(f"{selected_count} / {len(all_fields)} fields selected")
        else:
            st.info("Select a project to load fields.")

        # ── GOOGLE SHEET ──────────────────────────────────────────
        st.subheader("📊 Google Sheet Tab Name")
        sheet_name = st.text_input(
            "Sheet name", value=cfg.get("sheet", "Sheet1"),
            label_visibility="collapsed", placeholder="Sheet1",
        )

        # ── DATE RANGE ────────────────────────────────────────────
        st.subheader("📅 Date Range  (optional)")
        dc1, dc2 = st.columns(2)
        date_from = dc1.text_input("From (YYYY-MM-DD)",
                                    value=cfg.get("date_from", ""),
                                    placeholder="2024-01-01")
        date_to   = dc2.text_input("To   (YYYY-MM-DD)",
                                    value=cfg.get("date_to", ""),
                                    placeholder="2024-12-31")

        # ── SYNC INTERVAL ─────────────────────────────────────────
        st.subheader("⏱ Sync Interval")
        interval = st.slider(
            "Minutes", min_value=1, max_value=60,
            value=cfg.get("interval", 10),
            label_visibility="collapsed",
            format="%d min",
        )
        st.caption(f"Auto-sync every **{interval}** minute(s)")

        st.divider()

        # ── GENERATE ──────────────────────────────────────────────
        ready = bool(token and project)
        if st.button("▶  GENERATE APPS SCRIPT",
                     use_container_width=True,
                     type="primary",
                     disabled=not ready):

            d_from = date_from.strip() if date_pat.match(date_from.strip()) else ""
            d_to   = date_to.strip()   if date_pat.match(date_to.strip())   else ""

            fields_list = [
                f for f, v in st.session_state.get("sel_fields", {}).items() if v
            ] if all_fields else []

            script = generate_script(
                token=token,
                asset_uid=project["uid"],
                sheet_name=sheet_name or "Sheet1",
                fields_list=fields_list,
                date_from=d_from,
                date_to=d_to,
                interval=interval,
                kobo_url=kobo_url,
            )
            st.session_state["script"] = script

            save_cfg({
                "kobo_url":  kobo_url,
                "token":     token,
                "sheet":     sheet_name,
                "date_from": date_from,
                "date_to":   date_to,
                "interval":  interval,
            })
            st.success("✅ Script generated!")

    # ── RIGHT: Code output ────────────────────────────────────────
    with right:
        st.subheader("📜 Generated Apps Script")

        # Steps guide
        steps_html = """
        <div style="display:flex;gap:8px;flex-wrap:wrap;margin-bottom:12px">
          <span style="background:#1A3A5C;color:#7DD3FC;padding:4px 10px;border-radius:6px;font-size:12px;font-family:monospace">1 · Paste in Apps Script</span>
          <span style="background:#1A3A5C;color:#7DD3FC;padding:4px 10px;border-radius:6px;font-size:12px;font-family:monospace">2 · Save (Ctrl+S)</span>
          <span style="background:#1A3A5C;color:#7DD3FC;padding:4px 10px;border-radius:6px;font-size:12px;font-family:monospace">3 · Run setupTrigger() once</span>
          <span style="background:#1A3A5C;color:#7DD3FC;padding:4px 10px;border-radius:6px;font-size:12px;font-family:monospace">4 · Done ✓</span>
        </div>
        """
        st.markdown(steps_html, unsafe_allow_html=True)

        script = st.session_state.get("script", "")

        if script:
            # Code display
            st.code(script, language="javascript")

            # ── Two download/copy buttons ─────────────────────────
            b1, b2 = st.columns(2)

            # Button 1: Download .gs
            b1.download_button(
                label="⬇️  Download .gs file",
                data=script.encode("utf-8"),
                file_name="kobo_sync.gs",
                mime="text/plain",
                use_container_width=True,
                type="primary",
            )

            # Button 2: Copy to clipboard (via JS)
            copy_js = f"""
            <textarea id="gs-code" style="position:absolute;left:-9999px">{script.replace('`','\\`').replace('$','\\$')}</textarea>
            <button onclick="
              var t = document.getElementById('gs-code');
              t.select(); document.execCommand('copy');
              this.innerText = '✅ Copied!';
              setTimeout(()=>this.innerText='📋 Copy to Clipboard', 2000);
            " style="
              width:100%;padding:8px 0;background:#2563EB;color:#fff;
              border:none;border-radius:6px;font-size:14px;font-weight:600;
              cursor:pointer;font-family:monospace;
            ">📋 Copy to Clipboard</button>
            """
            with b2:
                components.html(copy_js, height=44)

        else:
            st.info("Fill in the settings on the left, then click **▶ GENERATE APPS SCRIPT**.")

            # Placeholder code block
            st.code(
                "// Fill settings on the left\n"
                "// then click GENERATE APPS SCRIPT\n",
                language="javascript"
            )


if __name__ == "__main__":
    main()
