name: Update Kobo Data

on:
  schedule:
    - cron: "*/10 * * * *"  # كل 10 دقائق
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install requests gspread google-auth

      - name: Run Script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          KOBO_TOKEN: ${{ secrets.KOBO_TOKEN }}
          KOBO_PROJECT: ${{ secrets.KOBO_PROJECT }}
          KOBO_FIELDS: ${{ secrets.KOBO_FIELDS }}
        run: |
          python live_data.py
